spring:
  application:
    name: ai
  ai:
    openai:
       api-key: dummy # as this is hosted by local LMS
       base-url: http://localhost:1234
       chat:
         options:
           model:
            - text-embedding-nomic-embed-text-v1.5
            - gemma-4-e4b
    vectorstore:
      pgvector:
        embedding-dimension: 768
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        content-size: 100000
  #r2dbc:
  datasource:
      url: jdbc:postgresql://localhost:5432/myvdb
      username: admin
      password: Sun1!america